import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientSideWrapper from "./ClientSideWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// This should be a server component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Client-side rendering */}
        <ClientSideWrapper>
          {children}
        </ClientSideWrapper>
      </body>
    </html>
  );
}
