import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import RootComponentWithProvider from './context/RootComponent';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  icons: 'logo.svg',
  title: 'GodHeranca',
  description: 'Generated by GodHeranca',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootComponentWithProvider>{children}</RootComponentWithProvider>
      </body>
    </html>
  );
}
