import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Footer from '@/components/Footer';
import ClientWrapper from '@/components/ClientWarapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'GodHeranca',
  description: 'Generated by GodHeranca',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ClientWrapper>
          {children}
        </ClientWrapper>
        <Footer />
      </body>
    </html>
  );
}
